[package]
name = "clojit_vm"
version = "0.0.1"
authors = ["Niklaus Zbinden <niklaus.zbinden@gmail.com>", "Sebastian Wicki <gandro@gmx.net>"]

[workspace]

[dependencies]

serde_json = "1.0.8"
serde = "1.0.26"
serde_derive = "1.0.26"
